export default {
  formId: "new-user-form",
  formField: {
    cedula: {
      name: "cedula",
      label: "Cédula de identidad",
      type: "number",
      placeholder: "Introducir el número de cédula",
      errorMsg: "El campo cédula es obligatorio.",
    },
    nombre: {
      name: "nombre",
      label: "Nombres",
      type: "text",
      placeholder: "ej. Micheal",
      errorMsg: "El campo Nombre es obligatorio.",
    },
    apellido: {
      name: "apellido",
      label: "Apellidos ",
      type: "text",
      placeholder: "ej. Matos",
      errorMsg: "El campo Apellido es obligatorio.",
    },
    email: {
      name: "email",
      label: "Correo Electrónico",
      type: "email",
      placeholder: "ej. soft@gmail.com",
      errorMsg: "El campo Correo Electrónico es obligatorio.",
      invalidMsg: "Su correo electrónico es incorrecto.",
    },
    regional: {
      name: "regional",
      label: "Regional educativa",
      type: "number",
      placeholder: "Seleccione una regional",
      errorMsg: "El Campo regional educativa es obligatorio.",
    },
    comision: {
      name: "comision",
      label: "Comisión",
      type: "number",
      placeholder: "Seleccione una de las comisiones",
      errorMsg: "El campo comisión es obligatorio.",
    },
    tipoMesa: {
      name: "tipoMesa",
      label: "Cargo",
      type: "text",
      placeholder: "Seleccione un cargo",
      errorMsg: "El campo cargo es obligatorio.",
    },
    rol: {
      name: "rol",
      label: "Rol de usuario",
      type: "number",
      placeholder: "Seleccione un rol",
      errorMsg: "El Campo Rol es obligatorio.",
    },
    contraseña: {
      name: "contraseña",
      label: "Contraseña",
      type: "password",
      placeholder: "Escriba su contraseña",
      errorMsg: "El campo contraseña es obligatorio.",
    },
    repetirContraseña: {
      name: "repetirContraseña",
      label: "Confirmar contraseña",
      type: "password",
      placeholder: "Confirma su contraseña",
      errorMsg: "El campo confirmar contraseña es obligatorio.",
    },
  },
};
